version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: school_management
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/school_management?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongodb_data: